require("duc-hoang.plugins-setup")
require("duc-hoang.core.options")
require("duc-hoang.core.keymaps")
require("duc-hoang.core.colorscheme")
require("duc-hoang.core.custom_commands")
require("duc-hoang.plugins.comment")
require("duc-hoang.plugins.nvim-tree")
require("duc-hoang.plugins.lualine")
require("duc-hoang.plugins.telescope")
require("duc-hoang.plugins.nvim-cmp")
require("duc-hoang.plugins.lsp.mason")
require("duc-hoang.plugins.lsp.lspconfig")
require("duc-hoang.plugins.lsp.lspsaga")
require("duc-hoang.plugins.gitsigns")
require("duc-hoang.plugins.gitblame")
require("duc-hoang.plugins.octo")
require("duc-hoang.plugins.others")
-- require("duc-hoang.plugins.avante")

